# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sascha/__DEV__/CppConsoleTest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sascha/__DEV__/CppConsoleTest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sascha/__DEV__/CppConsoleTest/CMakeFiles /home/sascha/__DEV__/CppConsoleTest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sascha/__DEV__/CppConsoleTest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Universal_IFR_Extractor

# Build rule for target.
Universal_IFR_Extractor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Universal_IFR_Extractor
.PHONY : Universal_IFR_Extractor

# fast build rule for target.
Universal_IFR_Extractor/fast:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/build
.PHONY : Universal_IFR_Extractor/fast

EFI.o: EFI.cpp.o
.PHONY : EFI.o

# target to build an object file
EFI.cpp.o:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/EFI.cpp.o
.PHONY : EFI.cpp.o

EFI.i: EFI.cpp.i
.PHONY : EFI.i

# target to preprocess a source file
EFI.cpp.i:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/EFI.cpp.i
.PHONY : EFI.cpp.i

EFI.s: EFI.cpp.s
.PHONY : EFI.s

# target to generate assembly for a file
EFI.cpp.s:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/EFI.cpp.s
.PHONY : EFI.cpp.s

UEFI.o: UEFI.cpp.o
.PHONY : UEFI.o

# target to build an object file
UEFI.cpp.o:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/UEFI.cpp.o
.PHONY : UEFI.cpp.o

UEFI.i: UEFI.cpp.i
.PHONY : UEFI.i

# target to preprocess a source file
UEFI.cpp.i:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/UEFI.cpp.i
.PHONY : UEFI.cpp.i

UEFI.s: UEFI.cpp.s
.PHONY : UEFI.s

# target to generate assembly for a file
UEFI.cpp.s:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/UEFI.cpp.s
.PHONY : UEFI.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Universal_IFR_Extractor.dir/build.make CMakeFiles/Universal_IFR_Extractor.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Universal_IFR_Extractor"
	@echo "... EFI.o"
	@echo "... EFI.i"
	@echo "... EFI.s"
	@echo "... UEFI.o"
	@echo "... UEFI.i"
	@echo "... UEFI.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

